config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :cocktails, only: [:index, :show, :new, :create] do
    resources :doses, only: [:new, :create]
  end
  delete 'doses/:id', to: 'doses#destroy', as: :dose
  root to: 'cocktails#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cocktail.rb
class Cocktail < ApplicationRecord
  validates :name, presence: true
  validates :name, uniqueness: true

  has_many :doses, dependent: :destroy
  has_many :ingredients, through: :doses
  has_one_attached :photo
end

app/models/dose.rb
class Dose < ApplicationRecord
  belongs_to :cocktail
  belongs_to :ingredient
  validates :description, presence: true
  validates :ingredient, uniqueness: { scope: :cocktail }
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  validates :name, uniqueness: true
  validates :name, presence: true
  has_many :doses
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cocktails_controller.rb
class CocktailsController < ApplicationController
  before_action :set_cocktail, only: [:show]
  def index
    @cocktails = Cocktail.all
  end

  def show
  end

  def new
    @cocktail = Cocktail.new
  end

  def create
    @cocktail = Cocktail.new(cocktail_params)
    if @cocktail.save
      redirect_to new_cocktail_dose_path(@cocktail)
    else
      render :new
    end
  end

  private

  def set_cocktail
    @cocktail = Cocktail.find(params[:id])
  end

  def cocktail_params
    params.require(:cocktail).permit(:name, :photo)
  end
end

app/controllers/doses_controller.rb
class DosesController < ApplicationController
  before_action :set_cocktail, only: [:new, :create]
  def new
    @dose = Dose.new
  end

  def create
    @dose = Dose.new(dose_params)
    @dose.cocktail = Cocktail.find(params[:cocktail_id])
    if @dose.save!
      redirect_to cocktail_path(@cocktail)
    else
      render :new
    end
  end

  def destroy
    @dose = Dose.find(params[:id])
    @dose.destroy

    redirect_to cocktail_path(@dose.cocktail)
  end

  private

  def set_cocktail
    @cocktail = Cocktail.find(params[:cocktail_id])
  end

  def dose_params
    params.require(:dose).permit(:description, :cocktail_id, :ingredient_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cocktails_helper.rb
module CocktailsHelper
end

app/helpers/doses_helper.rb
module DosesHelper
end

app/views/cocktails/index.html.erb
<div class="banner-index">
  <div class="container">
    <div class="row">
      <div class="col">
        <h2>Welcome to</h2>
        <h1>Cocktails</h2>
          <div>
            <%= link_to new_cocktail_path do  %>
            <div class="button button-purple">
              <i class="fa fa-cocktail"></i>
              Add <strong>Cocktail</strong>
            </div>

            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>

  <div class="container mt-3">

    <div class="cards">

      <% @cocktails.each do |cocktail| %>
      <div class="card-category link-to-text" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url('<%= cl_image_path cocktail.photo.key, height: 100, width: 200, crop: :fill %>')">
        <%= link_to "#{cocktail.name}", cocktail_path(cocktail), class: "link-to-text" %>
      </div>
      <% end %>

    </div>


















  </div>

app/views/cocktails/new.html.erb
<div class="d-flex container text-white justify-content-center ">
  <div class="row">
    <div class="col" style="margin: 32px;">
      <h1>New Cocktail</h1>
      <%= simple_form_for(@cocktail) do |f| %>
      <%= f.error_notification %>
      <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>
      <div class="form-inputs">
        <%= f.input :name %>
        <%= f.input :photo, as: :file %>
      </div>

      <div class="form-actions">
        <%= f.submit class: 'button button-purple' %>
      </div>
      <% end %>

      <%= link_to cocktails_path do%>
        <p class="button button-red">Back to the Cocktails</p>
      <% end %>

    </div>
  </div>
</div>

app/views/cocktails/show.html.erb
<div class="banner-show" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url('<%= cl_image_path @cocktail.photo.key, height: 300, width: 400, crop: :fill %>')"></div>

<div class="container text-white">

  <div class="row">
    <div class="col-6">
      <h2 class="m-3"><strong><%= @cocktail.name %></strong></h2>
    </div>
  </div>

  <div class="row">
    <div class="col-6">
      <%= link_to cocktails_path do%>
        <p class="button button-red">Back to Cocktails</p>
      <% end %>
    </div>
    <div class="col-6">
      <br>
      <p><strong>Ingredients:</strong></p>
    </div>
  </div>

  <div class="row">
    <div class="col-6 offset-6">
      <ul>
        <% @cocktail.doses.each do |dose| %>
        <li><%= dose.description %> <%= dose.ingredient.name %> <%= link_to dose_path(dose),
        method: :delete,
        data: { confirm: "Are you sure?" } do %>
        <i class="fas fa-trash ml-2"></i>
      </li>
      <% end %>
      <% end %>
    </ul>
  </div>
</div>

<div class="row">
  <div class="col-6 offset-6">
    <div class="ml-3">
    <%= link_to new_cocktail_dose_path(@cocktail) do %>
    <p class="button button-purple">Add Ingredients</p>
    <% end %>
    </div>
  </div>
</div>

</div>

app/views/doses/new.html.erb
<div class="d-flex container text-white justify-content-center">
  <div class="row">
    <div class="col" style="margin: 32px;">

     <h2>Add dose for <%= @cocktail.name %></h2>
     <%= simple_form_for([@cocktail, @dose]) do |f| %>
     <%= f.input :description %>
     <%= f.input :ingredient_id , collection: Ingredient.all %>
     <%= f.submit class: 'button button-purple' %>
     <% end %>


     <%= link_to cocktail_path(@cocktail) do%>
        <p class="button button-red">Back to the Cocktail</p>
      <% end %>
   </div>




 </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RailsMisterCocktail</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>

  <%= yield %>


  <%= javascript_include_tag "application" %> <!-- from app/assets/javascripts/application.js -->
  <%= javascript_pack_tag "application" %>
</body>
</html>